### ISSUE TITLE
Internal server error with Fortune 1.3.15

### ISSUE THREAD

**Issue by filippovdaniil** [thibremy/fortune-redis#3]
I tried to install an old version (1.3.15) of the Fortune.js (due to #2) and tested it with simple script:

```js
import fortune from 'fortune';
import redisAdapter from 'fortune-redis';
import express from 'express';
import cors from 'cors';

const server = express();
const store = fortune.create({ // Note: create() method is deprecated from 1.4.14
  adapter: {
    type: redisAdapter,
  },
});

store.defineType('post', {
  message: { type: String },
});

server.use(cors());
server.use(fortune.net.http(store));
store.connect().then(() => server.listen(1337));
```

— the server was started successfully, but when I made the POST-request to `http://localhost:1337/post` with json

```json
[
  {
    "message": "foo"
  }
]
```

I got the internal server error (without any errors in the terminal):

```json
{
  "name": "Error",
  "message": "An internal server error occurred."
}
```

while with the default adapter everything is ok:

```json
[
  {
    "id": "4f5124bc",
    "message": "foo"
  }
]
```

How can I fix this?

**Comment by thibremy** [comment]
Thanks for your report, I will investigate !

Which version of redis do you use ?
Can you try to run `npm test`?

**Comment by filippovdaniil** [comment]
Hi,

My version of the redis-server is 3.0.5:

```
$ redis-server --version
Redis server v=3.0.5 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=7c31d8dc2be1949e
```

I tried to run `npm test` — for the first time I got this babel error:

```
...

/tmp/fortune-redis-master/node_modules/babel-tape-runner/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /tmp/fortune-redis-master/test/index.js: Unknown option: /tmp/fortune-redis-master/package.json.nonStandard
    at Logger.error (/tmp/fortune-redis-master/node_modules/babel-tape-runner/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/tmp/fortune-redis-master/node_modules/babel-tape-runner/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    ...
```

So, I created the `.babelrc` file

```json
{
  "presets": ["es2015"]
}
```

and installed the `babel-preset-es2015` package. After that, I got another error:

```
...

xmodule.js:339
    throw err;
    ^

Error: Cannot find module 'redis'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    ...

  1 tests
  0 passed
  1 failed  

  Failed Tests:   There was 1 failure

    x no tests found
```

After some investigation, I found the cause of this error — at the first line in `lib/redis.js` there is an import from the `redis` package. So, I temporarily changed it to `fakeredis` and run `npm test` again:

```x  


  ---
  name: TypeError
  message: A is not a function
  stack:
    - at runTest (/tmp/fortune-redis-master/node_modules/fortune/dist/test/unit/adapter.js:393:17)
    - at /tmp/fortune-redis-master/node_modules/fortune/dist/test/unit/adapter.js:72:12
    - at process._tickCallback (node.js:366:9)
  ...
  

  1 tests
  0 passed
  1 failed  

  Failed Tests:   There was 1 failure

    x A is not a function
```

— I would be happy to provide any additional information you may need.

**Comment by yurykabanov** [comment]
Hi, @filippovdaniil asked me to test the project.
I'm using redis 2.8.4, node 4.2.2 and I've tried to run test with npm 2.14.7 and got mostly the same errors. Then I tried babel es2015 preset and had failing tests with no reason:
```

> fortune-redis@1.0.4 test /tmp/fortune-redis
> npm run lint; babel-tape-runner node test | tap-dot


> fortune-redis@1.0.4 lint /tmp/fortune-redis
> eslint lib

  ................
npm ERR! Test failed.  See above for more details.
``` 

After that I've updated my npm to the latest version (3.4.1) and using es2015 preset got strange error:
```

> fortune-redis@1.0.4 test /tmp/fortune-redis
> npm run lint; babel-tape-runner node test | tap-dot


> fortune-redis@1.0.4 lint /tmp/fortune-redis
> eslint lib

/tmp/fortune-redis/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/tmp/fortune-redis/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/tmp/fortune-redis/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/tmp/fortune-redis/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/tmp/fortune-redis/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/tmp/fortune-redis/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/tmp/fortune-redis/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/tmp/fortune-redis/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

  Failed: No assertions found.

npm ERR! Test failed.  See above for more details.
```

Finally, I've disabled this preset and had green tests:
```
> fortune-redis@1.0.4 test /tmp/fortune-redis
> npm run lint; babel-tape-runner node test | tap-dot


> fortune-redis@1.0.4 lint /tmp/fortune-redis
> eslint lib

  .......................................................

  55 tests
  55 passed

  Pass!
```

**Comment by thibremy** [comment]
Hello @yurykabanov,

Did you try it with this [hotfix branch ](https://github.com/thibremy/fortune-redis/tree/hotfix-%232) ?
I made this PR #4, now that's work on fortune.js 1.4.

I will test it with multi node/npm version.

Thanks for your feedback ;)

**Comment by yurykabanov** [comment]
Oh, I've just realized I've posted my results to the wrong issue...

Yes, I've tried this exactly with [hotfix branch](https://github.com/thibremy/fortune-redis/tree/hotfix-%232).

**Comment by thibremy** [comment]
My bad :)

I close this issue and keep trying to understand babel's errors.
